/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(Home)/': RouteRecordInfo<
      '/(Home)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(Home)/[...path]': RouteRecordInfo<
      '/(Home)/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/(Home)/about': RouteRecordInfo<
      '/(Home)/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/'
      | '/admin/employees/'
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/employees/': RouteRecordInfo<
      '/admin/employees/',
      '/admin/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(Home)/index.vue': {
      routes:
        | '/(Home)/'
      views:
        | never
    }
    'src/pages/(Home)/[...path].vue': {
      routes:
        | '/(Home)/[...path]'
      views:
        | never
    }
    'src/pages/(Home)/about.vue': {
      routes:
        | '/(Home)/about'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/'
        | '/admin/employees/'
      views:
        | 'default'
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/employees/index.vue': {
      routes:
        | '/admin/employees/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
