/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(Home)/': RouteRecordInfo<
      '/(Home)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(Home)/[...path]': RouteRecordInfo<
      '/(Home)/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/(Home)/about': RouteRecordInfo<
      '/(Home)/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/'
      | '/admin/auth/forgotPassword'
      | '/admin/auth/login'
      | '/admin/employee-roles/'
      | '/admin/employees/'
      | '/admin/employees/[id]'
      | '/admin/employees/add'
      | '/admin/employees/edit'
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/auth/forgotPassword': RouteRecordInfo<
      '/admin/auth/forgotPassword',
      '/admin/auth/forgotPassword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/auth/login': RouteRecordInfo<
      '/admin/auth/login',
      '/admin/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/employee-roles/': RouteRecordInfo<
      '/admin/employee-roles/',
      '/admin/employee-roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/employees/': RouteRecordInfo<
      '/admin/employees/',
      '/admin/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/employees/[id]': RouteRecordInfo<
      '/admin/employees/[id]',
      '/admin/employees/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/employees/add': RouteRecordInfo<
      '/admin/employees/add',
      '/admin/employees/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/employees/edit': RouteRecordInfo<
      '/admin/employees/edit',
      '/admin/employees/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(Home)/index.vue': {
      routes:
        | '/(Home)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(Home)/[...path].vue': {
      routes:
        | '/(Home)/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/(Home)/about.vue': {
      routes:
        | '/(Home)/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/'
        | '/admin/auth/forgotPassword'
        | '/admin/auth/login'
        | '/admin/employee-roles/'
        | '/admin/employees/'
        | '/admin/employees/[id]'
        | '/admin/employees/add'
        | '/admin/employees/edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/auth/forgotPassword.vue': {
      routes:
        | '/admin/auth/forgotPassword'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/auth/login.vue': {
      routes:
        | '/admin/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/employee-roles/index.vue': {
      routes:
        | '/admin/employee-roles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/employees/index.vue': {
      routes:
        | '/admin/employees/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/employees/[id].vue': {
      routes:
        | '/admin/employees/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/admin/employees/add.vue': {
      routes:
        | '/admin/employees/add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/employees/edit.vue': {
      routes:
        | '/admin/employees/edit'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
